feat: Image scanning in POST Ci script
devtron-labs/ci-runner pull request #103
Opened 2023-10-05 12:05 UTC by Ashish-devtron

2023-10-09 12:45 UTC, kartik-579 requested changes

2023-10-09 12:45 UTC, kartik-579 commented on ciStages.go
>  	err = os.Chdir("/")
create constant

2023-10-09 12:45 UTC, kartik-579 commented on ciStages.go
> +			}
can be extracted out

2023-10-09 12:45 UTC, kartik-579 commented on ciStages.go
> +	log.Println(util.DEVTRON, " /Build")
improve logs

2023-10-11 06:09 UTC, kartik-579 requested changes

2023-10-11 06:09 UTC, kartik-579 commented on ciStages.go
>  	if !buildSkipEnabled {
same condition repeated twice

2023-10-11 06:09 UTC, kartik-579 commented on ciStages.go
> +	if err != nil {
we are only handling the error found on last iteration, atleast log the errors found in previous iterations

2023-10-11 06:09 UTC, kartik-579 commented on ciStages.go
> +	for i := 0; i < imageRetryCountValue+1; i++ {
why imageRetryCountValue+1 ? we are starting the loop from 0

2023-10-11 07:38 UTC, kartik-579 approved these changes

2023-11-02 11:51 UTC, kartik-579 requested changes

2023-11-02 11:51 UTC, kartik-579 commented on ciStages.go
> +	resultsFromPlugin, err1 := extractOutResultsIfExists()
use err

2023-11-02 11:51 UTC, kartik-579 commented on ciStages.go
> +		err = runPostCiSteps(ciCdRequest, scriptEnvs, refStageMap, preCiStageOutVariable, metrics, artifactUploaded, dest, digest)
we are passing metrics by value here and above, are they going to be manipulated separately? if not please fix

2023-11-03 07:53 UTC, kartik-579 approved these changes

2023-11-03 09:30 UTC, kripanshdevtron approved these changes

2023-11-03 09:38 UTC, merged