added job name support in system variables in case of job
devtron-labs/ci-runner pull request #132
Opened 2024-04-01 09:53 UTC by Laeeqdev

2024-04-02 06:54 UTC, prakash100198 requested changes

2024-04-02 06:54 UTC, prakash100198 commented on executor/util/envUtils.go
> +		envs["JOB_NAME"] = cicdRequest.CommonWorkflowRequest.AppName
expose env variables conditionally based on job app name type and devtron app name, use IsJob in workflow event struct

2024-04-02 12:15 UTC, prakash100198 approved these changes

2024-04-09 07:15 UTC, kripanshdevtron approved these changes

2024-04-09 08:32 UTC, merged